### ISSUE TITLE
Order of /sources response?

### ISSUE THREAD

**Issue by ubergesundheit** [na-boa/brightsky#65]
Hi,

what is the order of the `/sources` response?

I can imagine it could be beneficial to set a default sorting of distance to given `lat`,`lon` parameters in ascending order.

If you want I could try to provide a PR.

**Comment by jdemaeyer** [comment]
Heyho Gerald,

the sources are first ordered by their observation type, then distance to the given lat/lon.

This is owed to the somewhat unintuitive distinction of sources and stations and necessary for prioritizing sources when retrieving historical or current weather (we don't want to return a forecast when an actual observation is available, even if the (imaginary) forecast station is closer than the observation station). 

For the `sources` endpoint it indeed seems more sensible to order by distance only, regardless of the observation type. If you want, feel free to submit a PR, otherwise I'll try to get it done towards the end of the week!

**Comment by ubergesundheit** [comment]
Thanks! Cool, I'll see when I have time to come up with something but I guess you'll be faster since I have no experience with tests in python. ;)
