### ISSUE TITLE
Age of forecasts?

### ISSUE THREAD

**Issue by ubergesundheit** [na-boa/brightsky#68]
Is it possible to show the age or generation timestamp of forecasts? Does this exist in the source data?

**Comment by jdemaeyer** [comment]
Yeah that is available in the sources. I'm a little hesitant to add this because there is currently no "clean" place where we could put it.

Adding a `last_updated` field for each source would be misleading because it wouldn't necessary reflect the age of a given weather record. E.g. at ~14:30, the forecast for 15:00 will have been generated around 14:20, but the forecast for 14:00 (which will still be the best data we have because the `current` observations have a lag of almost an hour) will have been generated around 13:20.

Adding a `last_updated` field for each record would not be 100 % accurate as well, because we gather a single `recent` or `historical` record from multiple sources, which may have different ages.

Lastly, adding one `last_updated` field per parameter (i.e. `temperature_last_updated`, `precipitation_last_updated`, ...) would be costly both storage and transfer size wise.

I wonder if we can find some way to make this available for forecasts only. E.g. by storing the generation date for each forecast timestamp in an extra table and splicing it in while generating the API response.

**Comment by ubergesundheit** [comment]
Mh, didn't thought about that. I guess once #63 is resolved, this shouldn't be such an issue any more. Feel free to close this.

**Comment by jdemaeyer** [comment]
Closing this as "wontfix" for now, feel free to re-open if this becomes more urgent
